name: Android Release Build

on:
  push:
    branches:
      - main # Or 'master', or your specific release branch
    tags:
      - 'v*.*.*' # Trigger on version tags like v1.0.0

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Decode Keystore
      run: echo "${{ secrets.SIGNING_KEYSTORE_BASE64 }}" | base64 --decode > app/release-key.jks
      # 'app/release-key.jks' is where your build.gradle will expect it.
      # The 'app/' prefix assumes your build.gradle is in the 'app' module.

    - name: Build Signed Release APK
      run: ./gradlew assembleRelease --stacktrace
      env:
        ORG_GRADLE_PROJECT_storeFile: ${{ github.workspace }}/app/release-key.jks
        ORG_GRADLE_PROJECT_storePassword: ${{ secrets.SIGNING_KEYSTORE_PASSWORD }}
        ORG_GRADLE_PROJECT_keyAlias: ${{ secrets.SIGNING_KEY_ALIAS }}
        ORG_GRADLE_PROJECT_keyPassword: ${{ secrets.SIGNING_KEY_PASSWORD }}

    - name: Capture build logs
      if: failure()
      run: |
        mkdir -p artifacts/logs
        cp -r app/build/reports artifacts/logs || true
        cp -r app/build/outputs/mapping/release artifacts/logs || true

    - name: Upload logs on failure
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: r8-fail-logs
        path: artifacts/logs

    - name: Upload Release APK
      if: success()
      uses: actions/upload-artifact@v4
      with:
        name: app-release-apk
        path: app/build/outputs/apk/release/*.apk
        retention-days: 7
